<a href="https://colab.research.google.com/github/Corey-Holton/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from sklearn.preprocessing import OneHotEncoder

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [ ]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [ ]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]


In [ ]:
# Create a list of at least 10 column names to use as X data
X_columns = ["Age", "HourlyRate", "DistanceFromHome", "Education", "EnvironmentSatisfaction", "WorkLifeBalance", "JobInvolvement", "JobLevel", "JobSatisfaction", "TotalWorkingYears", "NumCompaniesWorked", "YearsAtCompany"]

# Create X_df using selected columns
X_df = attrition_df[X_columns]

# Show the data types for X_df
X_df.dtypes


Age                        int64
HourlyRate                 int64
DistanceFromHome           int64
Education                  int64
EnvironmentSatisfaction    int64
WorkLifeBalance            int64
JobInvolvement             int64
JobLevel                   int64
JobSatisfaction            int64
TotalWorkingYears          int64
NumCompaniesWorked         int64
YearsAtCompany             int64
dtype: object

In [ ]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary


In [ ]:
# Create a StandardScaler
scaler = StandardScaler().fit(X_train)

# Fit the StandardScaler to the training data
X_train_scaled = scaler.transform(X_train)

# Scale the training and testing data
X_test_scaled = scaler.transform(X_test)


In [ ]:
# Create a OneHotEncoder for the Department column
department_ohe = OneHotEncoder(drop=None, handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the training data
department_ohe.fit(np.array(y_train['Department']).reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
# Transform both the training and testing data
y_train_department_encoded = department_ohe.transform(np.array(y_train['Department']).reshape(-1, 1))
y_test_department_encoded = department_ohe.transform(np.array(y_test['Department']).reshape(-1, 1))

# Display results
print("Training Data with Encoded Department:")
print(y_train_department_encoded) #.head() Changed to [:5] to display the first 5 elements

print("\nTesting Data with Encoded Department:")
print(y_test_department_encoded[:5]) #.head() Changed to [:5] to display the first 5 elements

Training Data with Encoded Department:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Testing Data with Encoded Department:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [ ]:
# Create a OneHotEncoder for the Attrition column
attrition_ohe = OneHotEncoder(drop=None, handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the training data
attrition_ohe.fit(np.array(y_train['Attrition']).reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attrition_encoded = attrition_ohe.transform(np.array(y_train['Attrition']).reshape(-1, 1))
y_test_attrition_encoded = attrition_ohe.transform(np.array(y_test['Attrition']).reshape(-1, 1))

# Display results

print("Training Data with Encoded Attrition:")
print(y_train_attrition_encoded[:5]) #.head() Changed to [:5] to display the first 5 elements

print("\nTesting Data with Encoded Attrition:")
print(y_test_attrition_encoded[:5]) #.head() Changed to [:5] to display the first 5 elements



Training Data with Encoded Attrition:
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]

Testing Data with Encoded Attrition:
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [ ]:
# Find the number of columns in the X training data
# Use shape attribute of the NumPy array to get number of columns
input_dim = X_train_scaled.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(input_dim,))

# Create at least two shared layers
shared_layer_1 = layers.Dense(64, activation='relu')(input_layer)
shared_layer_2 = layers.Dense(32, activation='relu')(shared_layer_1)

In [ ]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer = layers.Dense(16, activation='relu')(shared_layer_2)

# Create the output layer
dept_output_layer = layers.Dense(y_train_department_encoded.shape[1], activation='softmax', name='department_output')(dept_hidden_layer)


In [ ]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_hidden_layer = layers.Dense(16, activation='relu')(shared_layer_2)

# Create the output layer
attr_output_layer = layers.Dense(y_train_attrition_encoded.shape[1], activation='sigmoid', name='attrition_output')(attr_hidden_layer)


In [ ]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output_layer, attr_output_layer])

# Compile the model
model.compile(optimizer='adam', loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'}, metrics=['accuracy'])

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 12)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            832 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 32)             │          2,080 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             51 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             34 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 4,053 (15.83 KB)

 Trainable params: 4,053 (15.83 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
# Specify metrics for each output using a dictionary
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy',
                    'attrition_output': 'binary_crossentropy'},
              metrics={'department_output': 'accuracy',  # Accuracy for department prediction
                      'attrition_output': 'accuracy'})  # Accuracy for attrition prediction

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 12)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            832 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 32)             │          2,080 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             51 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             34 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 4,053 (15.83 KB)

 Trainable params: 4,053 (15.83 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
eval_results = model.evaluate(X_test_scaled, [y_test_department_encoded, y_test_attrition_encoded])


10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.5233 - department_output_accuracy: 0.3005 - loss: 1.8250 


In [26]:
# Print the accuracy for both department and attrition
# Extract the accuracy values
attrition_accuracy = eval_results[1]  # accuracy for attrition predictions
department_accuracy = eval_results[2]  # accuracy for department predictions

# Print the results in the desired format
print(f"Department predictions accuracy: {department_accuracy}")
print(f"Attrition predictions accuracy: {attrition_accuracy}")


Department predictions accuracy: 0.30612245202064514
Attrition predictions accuracy: 0.5408163070678711


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

1. Is accuracy the best metric to use on this data?

- Accuracy may not be the best metric if attrition is imbalanced (for instance, if there are far fewer "Yes" attrition cases than "No"). Precision and recall are often better suited for imbalanced data, as they focus on the correct classification of the minority class (in this case, attrition cases). The F1-score, a combination of precision and recall, can also offer a balanced view of model performance.

2. What activation functions did you choose for your output layers, and why?

- The softmax activation function was chosen for the department prediction (department_output), which is appropriate for multi-class classification, as it outputs probabilities that sum to 1 across classes. The sigmoid activation function was used for attrition prediction (attrition_output) because it is a binary classification task, producing a probability between 0 and 1 for each class.

3. Can you name a few ways that this model might be improved?

- **Experiment with additional features** to capture complex relationships, such as interaction terms between JobSatisfaction, EnvironmentSatisfaction, or YearsSinceLastPromotion.
- **Use regularization techniques** like dropout to prevent overfitting, especially if more layers are added.
- **Tune the model architecture** further, experimenting with different layer sizes or adding more layers to better capture patterns.
- **Consider ensemble methods** to combine predictions from multiple models, which may yield more accurate predictions, especially on difficult tasks like attrition prediction.